Refactor issue 1
Pia-Koester/katatraining pull request #3
Opened 2024-04-27 08:54 UTC by Pia-Koester

@Netznarkose ich habe jetzt die einzelnen Übungen jeweils in eine eigene Class gemacht und dann in Main genutzt. Schau mal ob das so besser ist :)

2024-04-27 19:53 UTC, Netznarkose requested changes
Super, das sieht schon viel aufgeräumter aus, aber der code braucht unbedingt code-formatierung
in intellij mach ich das so:
<img width="879" alt="Screenshot 2024-04-27 at 21 36 51" src="https://github.com/Pia-Koester/katatraining/assets/10247813/d63d3355-f577-446a-b6d3-7dd8131c6d86">

2024-04-27 22:12 UTC, Pia-Koester commented
@Netznarkose ich habe es mal ausprobiert, ein bisschen ordentlicher ist es geworden. Gibt es auch eine Möglichkeit das bei jedem speichern automatisch formatiert wird? Bei VS Code habe ich immer prettier genutzt.

2024-04-28 15:08 UTC, Netznarkose commented
⚠️ dem file katatraining/src/Space.java fehlt noch formatierung. 

> Gibt es auch eine Möglichkeit das bei jedem speichern automatisch formatiert wird? Bei VS Code habe ich immer prettier genutzt.

ich hab das [hier](https://stackoverflow.com/a/62349834) auf stackoverflow gefunden, mit dieser konfig wird dann bei jedem speichern der datei formatiert, suchst du sowas?
In meinem jetzigen intellij/java workflow benutze ich so viel autocompletion wie möglich, dann formatiert intellij auch gleich richtig und es gibt kaum noch stellen zu korrigieren, den rest erledige ich dann mit der der _reformat code action._

2024-04-30 07:03 UTC, Netznarkose commented
ps: du kannst auch rechts-klick auf den projekt folder machen und reformat code auswählen, dann weden direkt alle files des projekts formatiert.
<img width="480" alt="Screenshot 2024-04-30 at 09 02 18" src="https://github.com/Pia-Koester/katatraining/assets/10247813/b6392843-cab1-4d84-847c-630a9fffbb87">

2024-04-30 07:05 UTC, Netznarkose commented
PS: Ich habe schon den nächsten refactoring-issue vorbereitet, den möchte ich aber nicht posten solange dieser PR hier noch offen ist.

2024-04-30 10:53 UTC, Pia-Koester commented
@Netznarkose danke dir! Habe jetzt auch die letzte Datei erledigt. Kannst ja nochmal gucken. 
Ansonsten habe ich später noch einen anderen Branch mit neuen Katas.

2024-04-30 19:18 UTC, Netznarkose commented
Jetzt bitte noch thematisch zusammenhängende Commits wie
37663813b496ee5d1a2a7f8388cf89474bc4d322
3397b1a7adb63f5974b367ee2303ca7fc4c864ed
squashen, dann kann dieser PR in den main branch gemergt werden, imo.

2024-05-02 08:34 UTC, Netznarkose commented
Squashen von Commits geht auch auf der Kommandozeile und zwar mit einem interaktiven rebase `git rebase --interactive` 
aber das ist eine der Operationen, bei der ich gerne auf Gui Tools zurückgreife, weil diese sowas wesentlich einfacher machen. Intellij hat ein sehr gutes Git Tool eingebaut. Beim schnellen Suchen habe ich dieses Video* gefunden (aber nicht gesehen). Git Tower und andere Stand Alone Git Tools helfen dir auch bei sowas, aber wenn wir in diesem Kontext Intellij benutzen würde ich empfehlen es in in Intellij zu machen.
Über Sinn von squashes und allgemein git-history-pflege können wir uns ja mal bei eine der nächsten 1:1 Sessions unterhalten.

(*) https://www.jetbrains.com/guide/java/tutorials/marco-codes-git-tricks/git-squash/

2024-05-13 06:40 UTC, Netznarkose approved these changes

2024-05-13 06:41 UTC, merged